### ISSUE TITLE
Go Module Support

### ISSUE THREAD

**Issue by 1995parham** [RashadAnsari/go-grpc-example#1]
Is there any way to use this generator with the go module?

**Comment by RashadAnsari** [comment]
This project support go module but I said some definition for beginners.

**Comment by 1995parham** [comment]
@RashadAnsari Thanks for your explanation and this awesome example project.

**Comment by RashadAnsari** [comment]
> @RashadAnsari Thanks for your explanation and this awesome example project.

Thank you Parham.
