### ISSUE TITLE
Path Variable Support

### ISSUE THREAD

**Issue by 1995parham** [RashadAnsari/go-grpc-example#2]
GRPC has support for path variable, am I right?

https://github.com/RashadAnsari/go-grpc-example/blob/6fd1cc8960ee0fb54c48b0f82e4c8f8693a9ee8e/helloworld/helloworld.yml#L7

**Comment by RashadAnsari** [comment]
Yes, gRPC gateway support path parameter.

Below link is some reference that shows how gRPC gateway support path parameter.

https://github.com/grpc-ecosystem/grpc-gateway/blob/master/third_party/googleapis/google/api/http.proto

I use proto file instead of google api configuration file.
