### ISSUE TITLE
General Installation Method

### ISSUE THREAD

**Issue by 1995parham** [RashadAnsari/go-grpc-example#3]
Can you provide a general way for installation, that works on linux too?

https://github.com/RashadAnsari/go-grpc-example/blob/6fd1cc8960ee0fb54c48b0f82e4c8f8693a9ee8e/Makefile#L45

**Comment by RashadAnsari** [comment]
I solved this issue for Mac and Linux.

**Comment by 1995parham** [comment]
@RashadAnsari 💯
